apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: ech-0278-frontend-config
  namespace: ech-0278
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: PERMANENT_REDIRECT
