apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ech-0278
  namespace: ech-0278
  annotations:
    kubernetes.io/ingress.class: gce
    networking.gke.io/v1beta1.FrontendConfig: ech-0278-frontend-config
    networking.gke.io/managed-certificates: ech-0278-managed-cert
spec:
  rules:
    - host: ech-0278.gap-labs.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
