apiVersion: v1
kind: LimitRange
metadata:
  name: ech-0278-default-limits
  namespace: ech-0278
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      default:
        cpu: 500m
        memory: 512Mi
      max:
        cpu: "1"
        memory: 1Gi
