apiVersion: v1
kind: ResourceQuota
metadata:
  name: ech-0278-quota
  namespace: ech-0278
spec:
  hard:
    pods: "30"
    requests.cpu: "2"
    limits.cpu: "4"
    requests.memory: 2Gi
    limits.memory: 4Gi
